# Generated by Django 4.0.2 on 2022-03-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='products/generic/img_566093.png', max_length=255, null=True, upload_to='profiles/'),
        ),
    ]
