# Generated by Django 4.0.2 on 2022-05-12 04:09

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current_price',
            field=apps.products.models.PositiveFloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='in_storage',
            field=models.PositiveIntegerField(),
        ),
    ]
