# Generated by Django 4.0.2 on 2022-05-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_products_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_storage',
            field=models.IntegerField(),
        ),
    ]
