# Generated by Django 4.0.2 on 2022-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_products_in_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_storage',
            field=models.PositiveIntegerField(),
        ),
    ]
