# Generated by Django 4.0.2 on 2022-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_quantity_saledetails_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
