# Generated by Django 4.0.2 on 2022-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
