# Generated by Django 4.0.2 on 2022-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_sales_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
