# Generated by Django 4.0.2 on 2022-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetails',
            name='amount',
            field=models.FloatField(),
        ),
    ]
