# Generated by Django 4.0.2 on 2022-05-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_products_image'),
        ('sales', '0011_alter_saledetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sales'),
        ),
    ]
