# Generated by Django 4.0.2 on 2022-03-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='sale',
        ),
    ]
