# Generated by Django 4.0.2 on 2022-03-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
