# Generated by Django 4.0.2 on 2022-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customers_actual_deb_customers_max_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='actual_deb',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='max_credit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
