# Generated by Django 4.0.2 on 2022-05-20 06:04

import apps.customers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customers_actual_deb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='max_credit',
            field=apps.customers.models.PositiveFloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator('(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{4})')]),
        ),
    ]
