# Generated by Django 4.0.2 on 2022-03-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_sales_is_credit_sales_pyment_method'),
        ('customers', '0006_customers_actual_deb_customers_max_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('pyment_method', models.TextField(blank=True, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payments Details',
                'db_table': 'payments_details',
                'ordering': ['id'],
            },
        ),
    ]
