# Generated by Django 4.0.2 on 2022-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='pyment_method',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
