# Generated by Django 4.0.2 on 2022-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_adress_providers_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='phone',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
