# Generated by Django 4.0.2 on 2022-03-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedetails',
            options={'ordering': ['id'], 'verbose_name': 'purchase detail', 'verbose_name_plural': 'purchase details'},
        ),
        migrations.AlterModelTable(
            name='purchasedetails',
            table='purchase_details',
        ),
    ]
