# Generated by Django 4.0.2 on 2022-03-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchasedetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
