# Generated by Django 4.0.2 on 2022-03-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasedetails_discount_alter_purchasedetails_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
