name: Abinsco CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: abinsco
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name:  Run migrations
      run:  |
        python manage.py makemigrations
        python manage.py migrate
      
      env:
        SECRET_KEY: 'django-insecure-*ok*q$xn&#r-bb1nd$(!eb4f!t%gzr43+9#d4-eil#35dclz-t'
        DATABASE_NAME:  'abinsco'
        DATABASE_PORT:  '5432'
        DATABASE_USER:  'postgres'
        DATABASE_PASS:  'postgres'
        DATABASE_HOST:  'localhost'
    
    - name: Run Server
      run: python manage.py runserver &
    
    - name: Install Google Chrome 
      run: |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh
    - name: Run Tests
      run: |
        python manage.py test apps.sales.tests
        
    
