name: Abinsco CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: default
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name:  Run migrations & create superuser
      run:  |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py createsuperuser --noinput
      
      env:
        SECRET_KEY: 'django-insecure-*ok*q$xn&#r-bb1nd$(!eb4f!t%gzr43+9#d4-eil#35dclz-t'
        DATABASE_NAME:  'default'
        DATABASE_PORT:  '5432'
        DATABASE_USER:  'postgres'
        DATABASE_PASS:  'postgres'
        DATABASE_HOST:  'localhost'
        DJANGO_SUPERUSER_PASSWORD:  'test'
        DJANGO_SUPERUSER_EMAIL: 'test@test.com'
        DJANGO_SUPERUSER_USERNAME:  'test'
    
    - name: Run Server
      run: python manage.py runserver &
      env:
        SECRET_KEY: 'django-insecure-*ok*q$xn&#r-bb1nd$(!eb4f!t%gzr43+9#d4-eil#35dclz-t'
        DATABASE_NAME:  'default'
        DATABASE_PORT:  '5432'
        DATABASE_USER:  'postgres'
        DATABASE_PASS:  'postgres'
        DATABASE_HOST:  'localhost'
        
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@v1
    
    - name: Start XVFB
      run:  |
          Xvfb :99 &
          
    - name: Run Tests
      run: |
        python manage.py test apps.sales.tests
        
      env:
        SECRET_KEY: 'django-insecure-*ok*q$xn&#r-bb1nd$(!eb4f!t%gzr43+9#d4-eil#35dclz-t'
        DATABASE_NAME:  'default'
        DATABASE_PORT:  '5432'
        DATABASE_USER:  'postgres'
        DATABASE_PASS:  'postgres'
        DATABASE_HOST:  'localhost'
        DISPLAY: :99
        
    
